### GET запрос по фильмам (с пагинацией и сортировкой)
GET http://127.0.0.1:5000/movies/?status=new&page=2
Content-Type: application/json


### GET запрос по фильмам (с сортировкой)
GET http://127.0.0.1:5000/movies/?status=new
Content-Type: application/json


### GET запрос по режиссерам (с пагинацией)
GET http://127.0.0.1:5000/directors/?page=2
Content-Type: application/json


### GET запрос по жанрам (с пагинацией)
GET http://127.0.0.1:5000/genres/?page=2
Content-Type: application/json


### GET запрос по пользователям
GET http://127.0.0.1:5000/users/
Content-Type: application/json


### POST запрос на добавление пользователя
POST http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
    "email" : "email7@email.ru",
    "password" : "12345",
    "name" : "Sony",
    "surname" : "Li",
    "favorite_genre_id": 1
}


### POST запрос на авторизацию, с получением access_token и refresh_token
POST http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
    "name" : "Sony",
    "password" : "12345"
}


### PUT запрос на смену токена
###  1) подкидываем ДЕЙСВТУЮЩИЙ refresh_token,
###  2) получаем новую пару access_token, refresh_token
PUT http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
    "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiU29ueSIsImV4cCI6MTY2Mzc0NzE5MCwicmVmcmVzaF90b2tlbiI6dHJ1ZX0.S-vFrECfttc3ieWmoLU5Rxcbt3ZVoDotkARkUVlFrck"
}


